nohup: ignoring input
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
 * Restarting with stat
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
 * Debugger is active!
 * Debugger pin code: 470-998-420
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 248, in handle_one_request
    self.raw_requestline = self.rfile.readline()
IOError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 248, in handle_one_request
    self.raw_requestline = self.rfile.readline()
IOError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 248, in handle_one_request
    self.raw_requestline = self.rfile.readline()
IOError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 248, in handle_one_request
    self.raw_requestline = self.rfile.readline()
IOError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 217, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 248, in handle_one_request
    self.raw_requestline = self.rfile.readline()
IOError: [Errno 104] Connection reset by peer
220.181.171.88 - - [16/Nov/2015 19:31:27] "GET /favicon.ico HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 19:31:27] "GET /favicon.ico HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 19:42:43] "GET /favicon.ico HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 19:42:43] "GET /favicon.ico HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 19:49:46] "GET /order HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:49:46] "GET /static/css/bootstrap-datepicker.min.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:49:46] "GET /static/css/bootstrap3.min.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:49:46] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:49:46] "GET /static/css/style.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:49:46] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:49:46] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:49:53] "GET /order HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:50:02] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:50:09] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:50:14] "GET /static/img/sprite.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 19:50:14] "GET /static/img/logo_off.png HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 19:50:14] "GET /favicon.ico HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:06:31] "GET /favicon.ico HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:06:40] "POST /list HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:06:40] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:06:50] "POST /order HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/food-ordering-system/app/app.py", line 143, in order
    mail_content += str(order)
  File "/root/food-ordering-system/app/models.py", line 34, in __repr__
    return "%s\t%s\t%s\t%s\t%d" % (self.date, self.address, self.mobile, self.dish_name, self.qty)
AttributeError: 'Order' object has no attribute 'address'
123.118.2.82 - - [16/Nov/2015 21:06:50] "GET /order?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:06:50] "GET /order?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:06:50] "GET /order?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:06:51] "GET /order?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:06:51] "GET /order?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:06:52] "GET /order?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:06:55] "GET /list HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:07:01] "POST /list HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:07:01] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:07:04] "POST /order HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:07:05] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:07:07] "GET /list HTTP/1.1" 200 -
66.249.67.101 - - [16/Nov/2015 21:08:34] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/food-ordering-system/app/app.py", line 95, in index
    return render_template('menu.html', dish_list=menu.get_dish_list())
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: menu.html
220.181.171.88 - - [16/Nov/2015 21:33:42] "GET /favicon.ico HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:33:42] "GET /favicon.ico HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:34:44] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:34:44] "GET /static/css/bootstrap-datepicker.min.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:34:44] "GET /static/css/style.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:34:44] "GET /static/css/bootstrap3.min.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:34:51] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:34:51] "GET /static/img/sprite.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:35:02] "GET /static/img/logo_off.png HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:35:02] "GET /static/img/sprite.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:35:02] "GET /static/img/logo_off.png HTTP/1.1" 200 -
42.120.145.95 - - [16/Nov/2015 21:35:02] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/food-ordering-system/app/app.py", line 95, in index
    return render_template('menu.html', dish_list=menu.get_dish_list())
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 851, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: menu.html
220.181.171.88 - - [16/Nov/2015 21:37:19] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:37:19] "GET /static/img/sprite.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:38:41] "GET /static/img/logo_on.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:38:52] "POST /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:38:52] "GET /static/img/sprite.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:38:56] "GET /static/img/logo_on.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:38:57] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:38:57] "GET /static/img/sprite.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:38:57] "GET /static/img/logo_on.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:39:22] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:39:22] "GET /static/css/style.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:39:22] "GET /static/css/bootstrap3.min.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:39:22] "GET /static/css/bootstrap-datepicker.min.css HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:39:22] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:39:22] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:39:22] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:39:23] "GET /static/img/logo_off.png HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:40:04] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:40:22] "GET /static/img/sprite.png HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:45:43] "GET /favicon.ico HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:45:43] "GET /favicon.ico HTTP/1.1" 404 -
220.181.171.88 - - [16/Nov/2015 21:46:47] "GET /list HTTP/1.1" 200 -
220.181.171.88 - - [16/Nov/2015 21:47:02] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:47:45] "GET /list HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:47:45] "GET /static/css/bootstrap3.min.css HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:47:45] "GET /static/css/bootstrap-datepicker.min.css HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:47:45] "GET /static/css/style.css HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:47:45] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:47:45] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:47:45] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:47:46] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:47:46] "GET /static/img/logo_off.png HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:47:51] "GET /static/img/logo_on.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:48:00] "POST /list HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:48:00] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:48:06] "GET /static/img/logo_on.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:48:07] "GET /list HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:48:07] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:48:07] "GET /static/img/logo_on.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:50:50] "GET /list HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:50:50] "GET /static/css/bootstrap3.min.css HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:50:50] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:50:50] "GET /static/css/style.css HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:50:50] "GET /static/css/bootstrap-datepicker.min.css HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:50:50] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:50:50] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:50:51] "GET /static/img/logo_off.png HTTP/1.1" 304 -
123.118.2.82 - - [16/Nov/2015 21:50:51] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:50:52] "GET /static/img/logo_on.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:53:45] "POST /list HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:53:45] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:53:52] "POST /order HTTP/1.1" 200 -
123.118.2.82 - - [16/Nov/2015 21:53:53] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.2.82 - - [16/Nov/2015 21:53:53] "GET /static/img/logo_on.png HTTP/1.1" 404 -
45.63.121.31 - - [16/Nov/2015 22:28:53] "GET /list HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:28:53] "GET /static/css/bootstrap3.min.css HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:28:54] "GET /static/css/style.css HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:28:54] "GET /static/css/bootstrap-datepicker.min.css HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:28:54] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:28:54] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:28:55] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:29:02] "GET /static/img/sprite.png HTTP/1.1" 404 -
45.63.121.31 - - [16/Nov/2015 22:29:02] "GET /static/img/logo_off.png HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:29:07] "GET /favicon.ico HTTP/1.1" 404 -
45.63.121.31 - - [16/Nov/2015 22:29:19] "POST /list HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:29:22] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:29:22] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:29:22] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:29:24] "GET /static/img/sprite.png HTTP/1.1" 404 -
45.63.121.31 - - [16/Nov/2015 22:29:27] "POST /list HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:29:30] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:29:30] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:29:30] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:29:31] "GET /static/img/sprite.png HTTP/1.1" 404 -
45.63.121.31 - - [16/Nov/2015 22:29:44] "POST /order HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:29:56] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:29:56] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:29:56] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 304 -
45.63.121.31 - - [16/Nov/2015 22:30:17] "GET /static/img/logo_on.png HTTP/1.1" 404 -
45.63.121.31 - - [16/Nov/2015 22:30:24] "GET /static/img/sprite.png HTTP/1.1" 404 -
45.63.121.31 - - [16/Nov/2015 22:31:05] "POST /order HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/food-ordering-system/app/app.py", line 143, in order
    mail_content += str(order)
  File "/root/food-ordering-system/app/models.py", line 34, in __repr__
    return "%s\t%s\t%s\t%s\t%d" % (self.date, self.address, self.mobile, self.dish_name, self.qty)
AttributeError: 'Order' object has no attribute 'address'
45.63.121.31 - - [16/Nov/2015 22:31:05] "GET /static/img/logo_on.png HTTP/1.1" 404 -
45.63.121.31 - - [16/Nov/2015 22:31:05] "GET /order?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:31:05] "GET /order?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:31:05] "GET /order?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:31:07] "GET /order?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:31:08] "GET /order?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
45.63.121.31 - - [16/Nov/2015 22:31:09] "GET /order?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:02] "GET /favicon.ico HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 22:38:07] "GET /list HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:07] "GET /static/css/bootstrap3.min.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:07] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:07] "GET /static/css/style.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:07] "GET /static/css/bootstrap-datepicker.min.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:07] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:07] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:09] "GET /static/img/sprite.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 22:38:09] "GET /static/img/logo_off.png HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:38:10] "GET /favicon.ico HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 22:39:39] "POST /list HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:39:39] "GET /static/img/sprite.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 22:39:43] "POST /order HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:39:43] "GET /static/img/sprite.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 22:41:02] "GET /operate HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:41:02] "GET /operate HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:41:02] "GET /static/css/bootstrap.min.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:41:17] "GET /operate HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:41:39] "GET /operate HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:41:52] "GET /operate HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 22:42:25] "GET /static/img/logo_on.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 22:42:46] "GET /favicon.ico HTTP/1.1" 404 -
123.118.8.228 - - [16/Nov/2015 23:03:05] "GET /list HTTP/1.1" 200 -
123.118.8.228 - - [16/Nov/2015 23:03:14] "GET /list HTTP/1.1" 200 -
123.118.8.228 - - [16/Nov/2015 23:03:14] "GET /static/js/jquery.js HTTP/1.1" 200 -
123.118.8.228 - - [16/Nov/2015 23:03:14] "GET /static/js/jquery.js HTTP/1.1" 200 -
Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 185, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 166, in write
    self.wfile.write(data)
IOError: [Errno 32] Broken pipe
123.118.8.228 - - [16/Nov/2015 23:03:16] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.8.228 - - [16/Nov/2015 23:03:24] "GET /static/img/logo_on.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:03:43] "GET /list HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:43] "GET /static/css/bootstrap3.min.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:43] "GET /static/css/style.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:43] "GET /static/css/bootstrap-datepicker.min.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:43] "GET /static/js/jquery.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:45] "GET /static/js/bootstrap.min.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:45] "GET /static/js/bootstrap-datepicker.min.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:45] "GET /static/js/bootstrap-datepicker.zh-CN.min.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:47] "GET /static/img/logo_off.png HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:03:47] "GET /static/img/sprite.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:03:48] "GET /favicon.ico HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:04:05] "GET /list HTTP/1.1" 200 -
123.118.8.228 - - [16/Nov/2015 23:04:05] "POST /list HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:04:05] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.8.228 - - [16/Nov/2015 23:04:06] "POST /list HTTP/1.1" 200 -
123.118.8.228 - - [16/Nov/2015 23:04:06] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.8.228 - - [16/Nov/2015 23:04:09] "POST /list HTTP/1.1" 200 -
123.118.8.228 - - [16/Nov/2015 23:04:09] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.8.228 - - [16/Nov/2015 23:05:21] "GET /static/img/logo_on.png HTTP/1.1" 404 -
123.118.8.228 - - [16/Nov/2015 23:05:22] "GET /list HTTP/1.1" 200 -
123.118.8.228 - - [16/Nov/2015 23:05:22] "GET /static/img/sprite.png HTTP/1.1" 404 -
123.118.8.228 - - [16/Nov/2015 23:05:23] "GET /static/img/logo_on.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:05:40] "GET /list HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:05:40] "GET /static/img/sprite.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:06:18] "POST /list HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:18] "GET /static/img/sprite.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:06:23] "POST /order HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/food-ordering-system/app/app.py", line 143, in order
    mail_content += str(order)
  File "/root/food-ordering-system/app/models.py", line 34, in __repr__
    return "%s\t%s\t%s\t%s\t%d" % (self.date, self.address, self.mobile, self.dish_name, self.qty)
AttributeError: 'Order' object has no attribute 'address'
222.129.110.130 - - [16/Nov/2015 23:06:23] "GET /order?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:23] "GET /order?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:23] "GET /order?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:24] "GET /order?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:24] "GET /order?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:24] "GET /order?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:53] "GET /static/img/logo_on.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:06:55] "POST /order HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/food-ordering-system/app/app.py", line 143, in order
    mail_content += str(order)
  File "/root/food-ordering-system/app/models.py", line 34, in __repr__
    return "%s\t%s\t%s\t%s\t%d" % (self.date, self.address, self.mobile, self.dish_name, self.qty)
AttributeError: 'Order' object has no attribute 'address'
222.129.110.130 - - [16/Nov/2015 23:06:55] "GET /order?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:55] "GET /order?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:55] "GET /order?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:56] "GET /order?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:06:56] "GET /order?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:07:07] "GET /list HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:07:07] "GET /static/img/sprite.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:07:10] "POST /list HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:07:10] "GET /static/img/sprite.png HTTP/1.1" 404 -
222.129.110.130 - - [16/Nov/2015 23:07:29] "POST /order HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/food-ordering-system/app/app.py", line 143, in order
    mail_content += str(order)
  File "/root/food-ordering-system/app/models.py", line 34, in __repr__
    return "%s\t%s\t%s\t%s\t%d" % (self.date, self.address, self.mobile, self.dish_name, self.qty)
AttributeError: 'Order' object has no attribute 'address'
222.129.110.130 - - [16/Nov/2015 23:07:30] "GET /order?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:07:30] "GET /order?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:07:30] "GET /order?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:07:30] "GET /order?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
222.129.110.130 - - [16/Nov/2015 23:07:31] "GET /order?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
